// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monitoring.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    partial class MonitoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.BekendKunstwerkRow", b =>
                {
                    b.Property<string>("KunstwerkId")
                        .HasColumnType("text");

                    b.Property<DateTime>("BijgewerktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InGebruik")
                        .HasColumnType("boolean");

                    b.Property<string>("Locatie")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("KunstwerkId");

                    b.ToTable("bekend_kunstwerk", (string)null);
                });

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.IncidentRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Drempelwaarde")
                        .HasColumnType("double precision");

                    b.Property<string>("Ernst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GemetenWaarde")
                        .HasColumnType("double precision");

                    b.Property<string>("KunstwerkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OpgelostOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vervolgactie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KunstwerkId", "Status");

                    b.ToTable("incident", (string)null);
                });

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.MetingRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Eenheid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KunstwerkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessieId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Waarde")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("KunstwerkId", "Tijdstip");

                    b.ToTable("meting", (string)null);
                });

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.MonitoringRapportRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("KunstwerkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OpgesteldOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodeEind")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodeStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resultaten")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ZwaarsteOpenIncidentId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("monitoring_rapport", (string)null);
                });

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.MonitoringSessieRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AantalMetingen")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BeeindigdOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GestartOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KunstwerkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KunstwerkId");

                    b.ToTable("monitoring_sessie", (string)null);
                });

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.OutboxMessageRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Gepubliceerd")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GepubliceerdOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Gepubliceerd", "AangemaaktOp");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.VerwerktEventRow", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<DateTime>("VerwerktOp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("verwerkt_event", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
