// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monitoring.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    partial class MonitoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.BekendKunstwerkRow", b =>
                {
                    b.Property<string>("KunstwerkId")
                        .HasColumnType("text");

                    b.Property<DateTime>("BijgewerktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InGebruik")
                        .HasColumnType("boolean");

                    b.Property<string>("Locatie")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("KunstwerkId");

                    b.ToTable("bekend_kunstwerk", (string)null);
                });

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.OutboxMessageRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Gepubliceerd")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GepubliceerdOp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Gepubliceerd", "AangemaaktOp");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("Monitoring.Infrastructure.Persistence.Rows.VerwerktEventRow", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<DateTime>("VerwerktOp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("verwerkt_event", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
